### ISSUE TITLE
MVP Todo list

### ISSUE THREAD

**Issue by AndrewIngram** [onefinestay/django-mediacat#2]
Here's what we need to do!

Python:
- [x] Sort out the billion database query problem
- [x] Human-readable conversion of an associated object to a path, ie "Cities/Regions > London > Units > Wardour Street 3"
- [x] Implement new ImageMediaField
- [x] Extract metadata (EXIF tags, Lightroom tags etc) to the Media model on upload
- [x] setup.py

Javascript:
- [x] Edit existing crops
- [x] Create new crops
- [x] History replaceState when browsing categories
- [x] Upload files
- [x] Upload progress component
- [x] Scrollpane component 
- [x] Drag-drop creation of image/category associations
- [x] Image selection
- [x] Promote as much UI state as possible into its own store so that interactions can trigger changes when appropriate.
- [x] Keyboard navigation
- [x] Unify approach to interaction with web services, and how we hold onto requests.
- [x] Sorting of thumbnail list
- [x] Drag-drop re-ordering when in 'manual' sort mode.
- [x] Figure out the rounding bugs with cropping

Visuals:
- [x] Split styles into smaller modules to closely map to React components
- [x] Reduce dependency on the cascade for styling individual components.
- [x] Something other than a green square for dragging images
- [x] Make the selected image and crop more obviou.
